# Generated by Django 6.0.3 on 2026-04-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='profile_files/')),
                ('user_type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], max_length=20)),
                ('location', models.CharField(default='', max_length=255)),
                ('telephone', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('working_hours', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
